### ISSUE TITLE
Broken dependency chain

### ISSUE THREAD

**Issue by spiritway** [vinsonchuong/jasmine-es6#10]
register-module/index.js:8

for (const{name, path, main} of modules) {
               ^
unexpected token { 

Via dist-es6/lib/run.js:14

**Comment by spiritway** [comment]
Note: running windows

**Comment by vinsonchuong** [comment]
Thanks for the report! I don't usually use Windows; so, issues slip by from time to time. I'll configure a Windows VM and try to replicate this issue.

Until I'm able to fix this, vinsonchuong/jasmine-es6#7 for some hints on how to configure [jasmine-npm](https://github.com/jasmine/jasmine-npm) to transpile with Babel. Or, you can check out [AVA](https://github.com/avajs/ava), which supports transpilation out-of-the-box.

**Comment by spiritway** [comment]
Am able to get this working by doing, "babel-node \"./node_modules/bin/jasmine.js\" test.js", w/o this library.  Is there a clarification for what this library does that the above command does not?

**Comment by erkstruwe** [comment]
You probably mean `"babel-node \"./node_modules/jasmine/bin/jasmine.js\" test.js"` after having installed `babel-cli` as a devDependency.

**Comment by amandapouget** [comment]
Same issue. Running on Mac.

**Comment by vinsonchuong** [comment]
@spiritway raises a good point in that all this library does is

* Enable compilation using Babel by either loading `babel-register` or by running  `jasmine` using `babel-node`
* Wrap `beforeEach`, `afterEach`, `beforeAll`, `afterAll`, and `it` so that they support `async` functions.

Because Jasmine has no intentions to automatically work with ES.next and the solution that I've built involves complex workarounds, I think I want to deprecate this project.

I highly recommend users of this library to consider [AVA](https://github.com/avajs/ava), or use the data points in this issue to recover some of this functionality using vanilla `jasmine-npm`

**Comment by vinsonchuong** [comment]
I am going to close this as won't fix.
